### ISSUE TITLE
Left the keys in the ignition

### ISSUE THREAD

**Issue by spences10** [clarkhacks/Twitter-Bot#1]
Hey @clarkhacks I see you have your Twitter API keys on display 👌 😄 

Forgive me if you have already implemented something to exclude the keys from prying eyes but I was having a poke around and discovered them.

Have you you considered using an `.env` file with `dotenv`

https://github.com/clarkhacks/Twitter-Bot/blob/9144a6feee4f614252c6b09c7556bc0b96052dda/_retired/img-bot.js#L9

**Comment by spences10** [comment]
Nice bot by the way :👌

**Comment by clarkhacks** [comment]
Thank you so much for pointing this out. I recently switched from github to a private server and forgot all about this.
